baseURL = "/"
languageCode = "zh-cn"
DefaultContentLanguage = "zh"

title = "Nutanix实验室"
theme = "docdock"
#themesdir = "../.."

[params]
editURL = "https://github.com/Nutanix-lab/lab-guide/edit/master/content"
showVisitedLinks = true # default is false
themeStyle = "original" # "original" or "flex" # default "original"
themeVariant = "green" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>更多</h3>"
name = "<i class='fa fa-github'></i> Github代码库"
identifier = "ds"
url = "https://github.com/Nutanix-lab/lab-guide"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-camera'></i>友情链接"
url = "/showcase"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Nutanix实验室"
identifier = "nutanixlab"
url = "http://nutnaix.martinliu.cn/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fa fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30
